@baseUrl = http://localhost:5098
@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxMCIsInVuaXF1ZV9uYW1lIjoidGVzdDFAdGVzdC50ZXN0IiwiaHR0cDovL3NjaGVtYXMubWljcm9zb2Z0LmNvbS93cy8yMDA4LzA2L2lkZW50aXR5L2NsYWltcy9yb2xlIjoiUmVwb3J0ZXIiLCJleHAiOjE3ODE4MjYzNjgsImlzcyI6IkJ1Z0Jhc2VBcGkiLCJhdWQiOiJCdWdCYXNlQ2xpZW50In0.6iBgmKSG7Rpjo9h79W_8bz9jYL4Ayv5W9L44AgnvSOU

POST {{baseUrl}}/api/auth/register
Content-Type: application/json

{
  "username": "Johan",
  "email": "test3@test.com",
  "password": "Test123!"
}

### Login
POST {{baseUrl}}/api/auth/login
Content-Type: application/json

{
  "email": "test1@test.test",
  "password": "test"
}
//{
//  "email": "test@test.com",
//  "password": "Test123!"
//}





### Create project (requires token)
POST {{baseUrl}}/api/project
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "name": "Test Project",
  "description": "Ett testprojekt"
}

### Get all projects (requires token)
GET {{baseUrl}}/api/project
Authorization: Bearer {{token}}




### Create issue (requires token)
POST {{baseUrl}}/api/issue
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "projectId": 10,
  "title": "Test issue",
  "description": "En testissue",
  "priority": 2
}


### Get all issues (requires token)
GET {{baseUrl}}/api/issue
Authorization: Bearer {{token}}

### Get issue by id (requires token)
GET {{baseUrl}}/api/issue/6
Authorization: Bearer {{token}}

### Update issue (requires token)
PUT {{baseUrl}}/api/issue/4
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "status": 2
}


### Delete issue (requires token)
DELETE {{baseUrl}}/api/issue/3
Authorization: Bearer {{token}}



### Get all comments by issueId (requires token)
GET {{baseUrl}}/api/comment?issueId=6
Authorization: Bearer {{token}}


### Create comment (requires token)
POST {{baseUrl}}/api/comment
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "issueId": 6,
  "content": "En testkommentar"
}


### Update comment (requires token)
PUT {{baseUrl}}/api/comment/2
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "content": "Uppdaterad kommentar"
}

### Delete comment (requires token)
DELETE {{baseUrl}}/api/comment/2
Authorization: Bearer {{token}}